<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountryWithIsoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // All countries with ISO codes (from REST Countries API)
        $allCountries = [
            ["name" => "Jamaica", "cca2" => "JM"],
            ["name" => "Comoros", "cca2" => "KM"],
            ["name" => "Zimbabwe", "cca2" => "ZW"],
            ["name" => "Sint Maarten", "cca2" => "SX"],
            ["name" => "Laos", "cca2" => "LA"],
            ["name" => "Latvia", "cca2" => "LV"],
            ["name" => "Tajikistan", "cca2" => "TJ"],
            ["name" => "United Kingdom", "cca2" => "GB"],
            ["name" => "Nicaragua", "cca2" => "NI"],
            ["name" => "Sudan", "cca2" => "SD"],
            ["name" => "Greece", "cca2" => "GR"],
            ["name" => "Lithuania", "cca2" => "LT"],
            ["name" => "Rwanda", "cca2" => "RW"],
            ["name" => "Senegal", "cca2" => "SN"],
            ["name" => "Monaco", "cca2" => "MC"],
            ["name" => "Lesotho", "cca2" => "LS"],
            ["name" => "Tunisia", "cca2" => "TN"],
            ["name" => "Vanuatu", "cca2" => "VU"],
            ["name" => "Ecuador", "cca2" => "EC"],
            ["name" => "Kuwait", "cca2" => "KW"],
            ["name" => "Philippines", "cca2" => "PH"],
            ["name" => "Chile", "cca2" => "CL"],
            ["name" => "Bahamas", "cca2" => "BS"],
            ["name" => "Tanzania", "cca2" => "TZ"],
            ["name" => "Costa Rica", "cca2" => "CR"],
            ["name" => "Morocco", "cca2" => "MA"],
            ["name" => "Montenegro", "cca2" => "ME"],
            ["name" => "Micronesia", "cca2" => "FM"],
            ["name" => "Portugal", "cca2" => "PT"],
            ["name" => "United Arab Emirates", "cca2" => "AE"],
            ["name" => "Libya", "cca2" => "LY"],
            ["name" => "Luxembourg", "cca2" => "LU"],
            ["name" => "Jersey", "cca2" => "JE"],
            ["name" => "Solomon Islands", "cca2" => "SB"],
            ["name" => "Algeria", "cca2" => "DZ"],
            ["name" => "Antigua and Barbuda", "cca2" => "AG"],
            ["name" => "Saint Helena, Ascension and Tristan da Cunha", "cca2" => "SH"],
            ["name" => "Brazil", "cca2" => "BR"],
            ["name" => "South Georgia", "cca2" => "GS"],
            ["name" => "Mali", "cca2" => "ML"],
            ["name" => "Pakistan", "cca2" => "PK"],
            ["name" => "Trinidad and Tobago", "cca2" => "TT"],
            ["name" => "Armenia", "cca2" => "AM"],
            ["name" => "Bangladesh", "cca2" => "BD"],
            ["name" => "Turks and Caicos Islands", "cca2" => "TC"],
            ["name" => "Turkmenistan", "cca2" => "TM"],
            ["name" => "Faroe Islands", "cca2" => "FO"],
            ["name" => "Palau", "cca2" => "PW"],
            ["name" => "Cuba", "cca2" => "CU"],
            ["name" => "Chad", "cca2" => "TD"],
            ["name" => "Bosnia and Herzegovina", "cca2" => "BA"],
            ["name" => "Botswana", "cca2" => "BW"],
            ["name" => "Estonia", "cca2" => "EE"],
            ["name" => "British Indian Ocean Territory", "cca2" => "IO"],
            ["name" => "French Southern and Antarctic Lands", "cca2" => "TF"],
            ["name" => "Greenland", "cca2" => "GL"],
            ["name" => "Christmas Island", "cca2" => "CX"],
            ["name" => "Pitcairn Islands", "cca2" => "PN"],
            ["name" => "Western Sahara", "cca2" => "EH"],
            ["name" => "Montserrat", "cca2" => "MS"],
            ["name" => "Bahrain", "cca2" => "BH"],
            ["name" => "Dominican Republic", "cca2" => "DO"],
            ["name" => "United States", "cca2" => "US"],
            ["name" => "Cook Islands", "cca2" => "CK"],
            ["name" => "Colombia", "cca2" => "CO"],
            ["name" => "Guinea", "cca2" => "GN"],
            ["name" => "Ireland", "cca2" => "IE"],
            ["name" => "Maldives", "cca2" => "MV"],
            ["name" => "Panama", "cca2" => "PA"],
            ["name" => "Mozambique", "cca2" => "MZ"],
            ["name" => "Oman", "cca2" => "OM"],
            ["name" => "Czechia", "cca2" => "CZ"],
            ["name" => "Heard Island and McDonald Islands", "cca2" => "HM"],
            ["name" => "Saint Vincent and the Grenadines", "cca2" => "VC"],
            ["name" => "Haiti", "cca2" => "HT"],
            ["name" => "Nigeria", "cca2" => "NG"],
            ["name" => "British Virgin Islands", "cca2" => "VG"],
            ["name" => "Namibia", "cca2" => "NA"],
            ["name" => "Dominica", "cca2" => "DM"],
            ["name" => "Canada", "cca2" => "CA"],
            ["name" => "Guernsey", "cca2" => "GG"],
            ["name" => "Niger", "cca2" => "NE"],
            ["name" => "Indonesia", "cca2" => "ID"],
            ["name" => "Yemen", "cca2" => "YE"],
            ["name" => "Palestine", "cca2" => "PS"],
            ["name" => "Gabon", "cca2" => "GA"],
            ["name" => "Eritrea", "cca2" => "ER"],
            ["name" => "Cyprus", "cca2" => "CY"],
            ["name" => "Hong Kong", "cca2" => "HK"],
            ["name" => "Bouvet Island", "cca2" => "BV"],
            ["name" => "Slovakia", "cca2" => "SK"],
            ["name" => "Slovenia", "cca2" => "SI"],
            ["name" => "Niue", "cca2" => "NU"],
            ["name" => "Kiribati", "cca2" => "KI"],
            ["name" => "Germany", "cca2" => "DE"],
            ["name" => "Kosovo", "cca2" => "XK"],
            ["name" => "Ivory Coast", "cca2" => "CI"],
            ["name" => "Sri Lanka", "cca2" => "LK"],
            ["name" => "Saint Martin", "cca2" => "MF"],
            ["name" => "Belgium", "cca2" => "BE"],
            ["name" => "Israel", "cca2" => "IL"],
            ["name" => "Åland Islands", "cca2" => "AX"],
            ["name" => "Northern Mariana Islands", "cca2" => "MP"],
            ["name" => "Denmark", "cca2" => "DK"],
            ["name" => "Bermuda", "cca2" => "BM"],
            ["name" => "Gibraltar", "cca2" => "GI"],
            ["name" => "Syria", "cca2" => "SY"],
            ["name" => "Timor-Leste", "cca2" => "TL"],
            ["name" => "San Marino", "cca2" => "SM"],
            ["name" => "Gambia", "cca2" => "GM"],
            ["name" => "Peru", "cca2" => "PE"],
            ["name" => "Guinea-Bissau", "cca2" => "GW"],
            ["name" => "Sierra Leone", "cca2" => "SL"],
            ["name" => "Turkey", "cca2" => "TR"],
            ["name" => "Bolivia", "cca2" => "BO"],
            ["name" => "Norway", "cca2" => "NO"],
            ["name" => "Republic of the Congo", "cca2" => "CG"],
            ["name" => "Eswatini", "cca2" => "SZ"],
            ["name" => "Paraguay", "cca2" => "PY"],
            ["name" => "Ukraine", "cca2" => "UA"],
            ["name" => "Malaysia", "cca2" => "MY"],
            ["name" => "Tonga", "cca2" => "TO"],
            ["name" => "Benin", "cca2" => "BJ"],
            ["name" => "Sweden", "cca2" => "SE"],
            ["name" => "Tuvalu", "cca2" => "TV"],
            ["name" => "Mongolia", "cca2" => "MN"],
            ["name" => "South Africa", "cca2" => "ZA"],
            ["name" => "Curaçao", "cca2" => "CW"],
            ["name" => "Australia", "cca2" => "AU"],
            ["name" => "Saint Kitts and Nevis", "cca2" => "KN"],
            ["name" => "Ghana", "cca2" => "GH"],
            ["name" => "Iraq", "cca2" => "IQ"],
            ["name" => "Vietnam", "cca2" => "VN"],
            ["name" => "Guyana", "cca2" => "GY"],
            ["name" => "Azerbaijan", "cca2" => "AZ"],
            ["name" => "Cameroon", "cca2" => "CM"],
            ["name" => "Egypt", "cca2" => "EG"],
            ["name" => "Iceland", "cca2" => "IS"],
            ["name" => "Venezuela", "cca2" => "VE"],
            ["name" => "Barbados", "cca2" => "BB"],
            ["name" => "Falkland Islands", "cca2" => "FK"],
            ["name" => "Malawi", "cca2" => "MW"],
            ["name" => "Kyrgyzstan", "cca2" => "KG"],
            ["name" => "Taiwan", "cca2" => "TW"],
            ["name" => "Bulgaria", "cca2" => "BG"],
            ["name" => "North Korea", "cca2" => "KP"],
            ["name" => "Andorra", "cca2" => "AD"],
            ["name" => "Angola", "cca2" => "AO"],
            ["name" => "Saint Barthélemy", "cca2" => "BL"],
            ["name" => "Russia", "cca2" => "RU"],
            ["name" => "Burkina Faso", "cca2" => "BF"],
            ["name" => "Vatican City", "cca2" => "VA"],
            ["name" => "Isle of Man", "cca2" => "IM"],
            ["name" => "Afghanistan", "cca2" => "AF"],
            ["name" => "Croatia", "cca2" => "HR"],
            ["name" => "Bhutan", "cca2" => "BT"],
            ["name" => "Belarus", "cca2" => "BY"],
            ["name" => "Cocos (Keeling) Islands", "cca2" => "CC"],
            ["name" => "New Zealand", "cca2" => "NZ"],
            ["name" => "Madagascar", "cca2" => "MG"],
            ["name" => "Thailand", "cca2" => "TH"],
            ["name" => "Georgia", "cca2" => "GE"],
            ["name" => "India", "cca2" => "IN"],
            ["name" => "China", "cca2" => "CN"],
            ["name" => "Saint Pierre and Miquelon", "cca2" => "PM"],
            ["name" => "Puerto Rico", "cca2" => "PR"],
            ["name" => "Djibouti", "cca2" => "DJ"],
            ["name" => "Saudi Arabia", "cca2" => "SA"],
            ["name" => "Iran", "cca2" => "IR"],
            ["name" => "Zambia", "cca2" => "ZM"],
            ["name" => "Ethiopia", "cca2" => "ET"],
            ["name" => "Macau", "cca2" => "MO"],
            ["name" => "Guatemala", "cca2" => "GT"],
            ["name" => "Martinique", "cca2" => "MQ"],
            ["name" => "Suriname", "cca2" => "SR"],
            ["name" => "Uruguay", "cca2" => "UY"],
            ["name" => "Italy", "cca2" => "IT"],
            ["name" => "New Caledonia", "cca2" => "NC"],
            ["name" => "Fiji", "cca2" => "FJ"],
            ["name" => "Aruba", "cca2" => "AW"],
            ["name" => "São Tomé and Príncipe", "cca2" => "ST"],
            ["name" => "Switzerland", "cca2" => "CH"],
            ["name" => "DR Congo", "cca2" => "CD"],
            ["name" => "Finland", "cca2" => "FI"],
            ["name" => "Malta", "cca2" => "MT"],
            ["name" => "El Salvador", "cca2" => "SV"],
            ["name" => "Jordan", "cca2" => "JO"],
            ["name" => "Tokelau", "cca2" => "TK"],
            ["name" => "Nauru", "cca2" => "NR"],
            ["name" => "Poland", "cca2" => "PL"],
            ["name" => "Mauritania", "cca2" => "MR"],
            ["name" => "Wallis and Futuna", "cca2" => "WF"],
            ["name" => "Antarctica", "cca2" => "AQ"],
            ["name" => "Guam", "cca2" => "GU"],
            ["name" => "North Macedonia", "cca2" => "MK"],
            ["name" => "Togo", "cca2" => "TG"],
            ["name" => "Myanmar", "cca2" => "MM"],
            ["name" => "Qatar", "cca2" => "QA"],
            ["name" => "France", "cca2" => "FR"],
            ["name" => "Mayotte", "cca2" => "YT"],
            ["name" => "Norfolk Island", "cca2" => "NF"],
            ["name" => "Seychelles", "cca2" => "SC"],
            ["name" => "Moldova", "cca2" => "MD"],
            ["name" => "South Sudan", "cca2" => "SS"],
            ["name" => "Brunei", "cca2" => "BN"],
            ["name" => "Japan", "cca2" => "JP"],
            ["name" => "Grenada", "cca2" => "GD"],
            ["name" => "Spain", "cca2" => "ES"],
            ["name" => "Caribbean Netherlands", "cca2" => "BQ"],
            ["name" => "Papua New Guinea", "cca2" => "PG"],
            ["name" => "Uzbekistan", "cca2" => "UZ"],
            ["name" => "Argentina", "cca2" => "AR"],
            ["name" => "South Korea", "cca2" => "KR"],
            ["name" => "Belize", "cca2" => "BZ"],
            ["name" => "Réunion", "cca2" => "RE"],
            ["name" => "Mexico", "cca2" => "MX"],
            ["name" => "United States Virgin Islands", "cca2" => "VI"],
            ["name" => "Serbia", "cca2" => "RS"],
            ["name" => "United States Minor Outlying Islands", "cca2" => "UM"],
            ["name" => "Cape Verde", "cca2" => "CV"],
            ["name" => "Cambodia", "cca2" => "KH"],
            ["name" => "Romania", "cca2" => "RO"],
            ["name" => "Hungary", "cca2" => "HU"],
            ["name" => "Marshall Islands", "cca2" => "MH"],
            ["name" => "Somalia", "cca2" => "SO"],
            ["name" => "Albania", "cca2" => "AL"],
            ["name" => "French Polynesia", "cca2" => "PF"],
            ["name" => "Burundi", "cca2" => "BI"],
            ["name" => "Central African Republic", "cca2" => "CF"],
            ["name" => "French Guiana", "cca2" => "GF"],
            ["name" => "American Samoa", "cca2" => "AS"],
            ["name" => "Saint Lucia", "cca2" => "LC"],
            ["name" => "Uganda", "cca2" => "UG"],
            ["name" => "Honduras", "cca2" => "HN"],
            ["name" => "Kazakhstan", "cca2" => "KZ"],
            ["name" => "Kenya", "cca2" => "KE"],
            ["name" => "Samoa", "cca2" => "WS"],
            ["name" => "Nepal", "cca2" => "NP"],
            ["name" => "Equatorial Guinea", "cca2" => "GQ"],
            ["name" => "Lebanon", "cca2" => "LB"],
            ["name" => "Mauritius", "cca2" => "MU"],
            ["name" => "Liechtenstein", "cca2" => "LI"],
            ["name" => "Cayman Islands", "cca2" => "KY"],
            ["name" => "Anguilla", "cca2" => "AI"],
            ["name" => "Guadeloupe", "cca2" => "GP"],
            ["name" => "Austria", "cca2" => "AT"],
            ["name" => "Netherlands", "cca2" => "NL"],
            ["name" => "Svalbard and Jan Mayen", "cca2" => "SJ"],
            ["name" => "Singapore", "cca2" => "SG"],
            ["name" => "Liberia", "cca2" => "LR"]
        ];

        $data = [];
        $now = Carbon::now();

        $nameNormalization = [
            'DR Congo' => 'Democratic Republic of the Congo',
            'Cape Verde' => 'Cabo Verde',
            'São Tomé and Príncipe' => 'Sao Tome and Principe',
        ];

        foreach ($allCountries as $country) {
            $normalizedName = $nameNormalization[$country['name']] ?? $country['name'];

            $data[] = [
                'name' => $normalizedName,
                'status' => 'Active',
                'iso_code' => $country['cca2'],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        foreach ($data as $countryData) {
            DB::table('countries')->updateOrInsert(
                ['name' => $countryData['name']],
                [
                    'status' => $countryData['status'],
                    'iso_code' => $countryData['iso_code'],
                    'updated_at' => $countryData['updated_at'],
                    'created_at' => $countryData['created_at'],
                ]
            );
        }
    }
}
