<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class Sic7CodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $sic7Codes = [
            // Agriculture, Forestry and Fishing
            ['code' => '01110', 'description' => 'Growing of cereals (except rice), leguminous crops and oil seeds', 'category' => 'Agriculture'],
            ['code' => '01120', 'description' => 'Growing of rice', 'category' => 'Agriculture'],
            ['code' => '01130', 'description' => 'Growing of vegetables and melons, roots, and tubers', 'category' => 'Agriculture'],
            ['code' => '01140', 'description' => 'Growing of sugar cane', 'category' => 'Agriculture'],
            ['code' => '01150', 'description' => 'Growing of tobacco', 'category' => 'Agriculture'],
            ['code' => '01160', 'description' => 'Growing of fibre crops', 'category' => 'Agriculture'],
            ['code' => '01190', 'description' => 'Growing of other non-perennial crops', 'category' => 'Agriculture'],
            ['code' => '01210', 'description' => 'Growing of grapes', 'category' => 'Agriculture'],
            ['code' => '01220', 'description' => 'Growing of tropical and subtropical fruits', 'category' => 'Agriculture'],
            ['code' => '01230', 'description' => 'Growing of citrus fruits', 'category' => 'Agriculture'],
            ['code' => '01240', 'description' => 'Growing of pome fruits and stone fruits', 'category' => 'Agriculture'],
            ['code' => '01250', 'description' => 'Growing of other tree and bush fruits and nuts', 'category' => 'Agriculture'],
            ['code' => '01260', 'description' => 'Growing of oleaginous fruits', 'category' => 'Agriculture'],
            ['code' => '01270', 'description' => 'Growing of beverage crops', 'category' => 'Agriculture'],
            ['code' => '01280', 'description' => 'Growing of spices, aromatic, drug, and pharmaceutical crops', 'category' => 'Agriculture'],
            ['code' => '01290', 'description' => 'Growing of other perennial crops', 'category' => 'Agriculture'],
            ['code' => '01300', 'description' => 'Plant propagation', 'category' => 'Agriculture'],
            ['code' => '01410', 'description' => 'Raising of cattle and buffaloes', 'category' => 'Animal Production'],
            ['code' => '01420', 'description' => 'Raising of horses and other equines', 'category' => 'Animal Production'],
            ['code' => '01430', 'description' => 'Raising of camels and camelids', 'category' => 'Animal Production'],
            ['code' => '01440', 'description' => 'Raising of sheep and goats', 'category' => 'Animal Production'],
            ['code' => '01450', 'description' => 'Raising of swine/pigs', 'category' => 'Animal Production'],
            ['code' => '01460', 'description' => 'Raising of poultry', 'category' => 'Animal Production'],
            ['code' => '01490', 'description' => 'Raising of other animals', 'category' => 'Animal Production'],
            ['code' => '01500', 'description' => 'Mixed farming', 'category' => 'Agriculture'],
            ['code' => '01610', 'description' => 'Support activities for crop production', 'category' => 'Agriculture Support'],
            ['code' => '01620', 'description' => 'Support activities for animal production', 'category' => 'Agriculture Support'],
            ['code' => '01630', 'description' => 'Post-harvest crop activities', 'category' => 'Agriculture Support'],
            ['code' => '01640', 'description' => 'Seed processing for propagation', 'category' => 'Agriculture Support'],
            ['code' => '01700', 'description' => 'Hunting, trapping and related service activities', 'category' => 'Forestry'],
            ['code' => '02100', 'description' => 'Silviculture and other forestry activities', 'category' => 'Forestry'],
            ['code' => '02200', 'description' => 'Logging', 'category' => 'Forestry'],
            ['code' => '02300', 'description' => 'Gathering of non-wood forest products', 'category' => 'Forestry'],
            ['code' => '02400', 'description' => 'Support services to forestry', 'category' => 'Forestry'],
            ['code' => '03110', 'description' => 'Marine fishing', 'category' => 'Fishing'],
            ['code' => '03120', 'description' => 'Freshwater fishing', 'category' => 'Fishing'],
            ['code' => '03210', 'description' => 'Marine aquaculture', 'category' => 'Fishing'],
            ['code' => '03220', 'description' => 'Freshwater aquaculture', 'category' => 'Fishing'],

            // Mining and Quarrying
            ['code' => '05100', 'description' => 'Mining of hard coal', 'category' => 'Mining'],
            ['code' => '05200', 'description' => 'Mining of lignite', 'category' => 'Mining'],
            ['code' => '06100', 'description' => 'Extraction of crude petroleum', 'category' => 'Oil and Gas'],
            ['code' => '06200', 'description' => 'Extraction of natural gas', 'category' => 'Oil and Gas'],
            ['code' => '07100', 'description' => 'Mining of iron ores', 'category' => 'Metal Ores'],
            ['code' => '07210', 'description' => 'Mining of uranium and thorium ores', 'category' => 'Metal Ores'],
            ['code' => '07291', 'description' => 'Mining of gold', 'category' => 'Metal Ores'],
            ['code' => '07292', 'description' => 'Mining of chrome', 'category' => 'Metal Ores'],
            ['code' => '07293', 'description' => 'Mining of copper', 'category' => 'Metal Ores'],
            ['code' => '07294', 'description' => 'Mining of manganese', 'category' => 'Metal Ores'],
            ['code' => '07295', 'description' => 'Mining of platinum group metals', 'category' => 'Metal Ores'],
            ['code' => '07299', 'description' => 'Other mining of non-ferrous metal ores n.e.c.', 'category' => 'Metal Ores'],
            ['code' => '08101', 'description' => 'Quarrying of dimension stone', 'category' => 'Quarrying'],
            ['code' => '08102', 'description' => 'Quarrying of limestone and lime works', 'category' => 'Quarrying'],
            ['code' => '08109', 'description' => 'Other quarrying of stone, sand, and clay', 'category' => 'Quarrying'],
            ['code' => '08911', 'description' => 'Mining of phosphates', 'category' => 'Chemical Minerals'],
            ['code' => '08919', 'description' => 'Other mining of chemical and fertilizer minerals', 'category' => 'Chemical Minerals'],
            ['code' => '08920', 'description' => 'Extraction of peat', 'category' => 'Other Mining'],
            ['code' => '08930', 'description' => 'Extraction of salt', 'category' => 'Other Mining'],
            ['code' => '08991', 'description' => 'Mining of diamonds', 'category' => 'Precious Stones'],
            ['code' => '08992', 'description' => 'Mining of precious and semi-precious stones, except diamonds', 'category' => 'Precious Stones'],
            ['code' => '08999', 'description' => 'Other mining and quarrying n.e.c.', 'category' => 'Other Mining'],
            ['code' => '09100', 'description' => 'Support activities for petroleum and natural gas extraction', 'category' => 'Mining Support'],
            ['code' => '09901', 'description' => 'Service activities incidental to mining of minerals on a fee or contract basis', 'category' => 'Mining Support'],
            ['code' => '09909', 'description' => 'Other support activities for other mining and quarrying n.e.c.', 'category' => 'Mining Support'],

            // Manufacturing - Food Products
            ['code' => '10101', 'description' => 'Slaughtering, dressing, and packing of livestock, including poultry and small game for meat', 'category' => 'Food Manufacturing'],
            ['code' => '10102', 'description' => 'Manufacture of prepared and preserved meat, including sausage; by-products (hides, bones, etc.)', 'category' => 'Food Manufacturing'],
            ['code' => '10103', 'description' => 'Production of lard and other edible fats', 'category' => 'Food Manufacturing'],
            ['code' => '10109', 'description' => 'Other processing and preserving of meat', 'category' => 'Food Manufacturing'],
            ['code' => '10200', 'description' => 'Processing and preserving of fish, crustaceans, and molluscs', 'category' => 'Food Manufacturing'],
            ['code' => '10300', 'description' => 'Processing and preserving of fruit and vegetables', 'category' => 'Food Manufacturing'],
            ['code' => '10401', 'description' => 'Manufacture of crude oil and oilseed cake and meal', 'category' => 'Food Manufacturing'],
            ['code' => '10402', 'description' => 'Manufacture of compound cooking fats, margarine, and edible oils', 'category' => 'Food Manufacturing'],
            ['code' => '10501', 'description' => 'Processing of fresh milk', 'category' => 'Food Manufacturing'],
            ['code' => '10502', 'description' => 'Manufacture of butter and cheese', 'category' => 'Food Manufacturing'],
            ['code' => '10503', 'description' => 'Manufacture of ice cream and other edible ice (whether or not containing cream or chocolate)', 'category' => 'Food Manufacturing'],
            ['code' => '10504', 'description' => 'Manufacture of milk powder, condensed milk, and other edible milk products, e.g. ghee, casein, or lactose', 'category' => 'Food Manufacturing'],
            ['code' => '10611', 'description' => 'Manufacture of flour and grain mill products, including rice and vegetable milling; grain mill residues', 'category' => 'Food Manufacturing'],
            ['code' => '10612', 'description' => 'Manufacture of breakfast foods', 'category' => 'Food Manufacturing'],
            ['code' => '10620', 'description' => 'Manufacture of starches and starch products', 'category' => 'Food Manufacturing'],
            ['code' => '10710', 'description' => 'Manufacture of bakery products', 'category' => 'Food Manufacturing'],
            ['code' => '10720', 'description' => 'Manufacture of sugar', 'category' => 'Food Manufacturing'],
            ['code' => '10730', 'description' => 'Manufacture of cocoa, chocolate, and sugar confectionery', 'category' => 'Food Manufacturing'],
            ['code' => '10740', 'description' => 'Manufacture of macaroni, noodles, couscous, and similar farinaceous products', 'category' => 'Food Manufacturing'],
            ['code' => '10750', 'description' => 'Manufacture of prepared meals and dishes', 'category' => 'Food Manufacturing'],
            ['code' => '10791', 'description' => 'Manufacture of coffee, coffee substitutes and tea', 'category' => 'Food Manufacturing'],
            ['code' => '10792', 'description' => 'Manufacture of nut foods', 'category' => 'Food Manufacturing'],
            ['code' => '10799', 'description' => 'Manufacture of spices, condiments, vinegar, yeast, egg products, soups, and other food', 'category' => 'Food Manufacturing'],
            ['code' => '10800', 'description' => 'Manufacture of prepared animal feeds', 'category' => 'Food Manufacturing'],

            // Beverages and Tobacco
            ['code' => '11010', 'description' => 'Distilling, rectifying, and blending of spirits', 'category' => 'Beverages'],
            ['code' => '11020', 'description' => 'Manufacture of wines', 'category' => 'Beverages'],
            ['code' => '11031', 'description' => 'Manufacture of malt liquors such as beer, ale, porter, and stout', 'category' => 'Beverages'],
            ['code' => '11032', 'description' => 'Manufacture of sorghum beer', 'category' => 'Beverages'],
            ['code' => '11033', 'description' => 'Manufacture of malt', 'category' => 'Beverages'],
            ['code' => '11040', 'description' => 'Manufacture of soft drinks; production of mineral waters and other bottled waters', 'category' => 'Beverages'],
            ['code' => '12000', 'description' => 'Manufacture of tobacco products', 'category' => 'Tobacco'],

            // Textiles and Clothing
            ['code' => '13111', 'description' => 'Preparatory activities in respect of animal fibres, including washing, combing', 'category' => 'Textiles'],
            ['code' => '13112', 'description' => 'Preparatory activities in respect of vegetable fibres', 'category' => 'Textiles'],
            ['code' => '13119', 'description' => 'Other preparation and spinning of textile fibres', 'category' => 'Textiles'],
            ['code' => '13120', 'description' => 'Weaving of textiles', 'category' => 'Textiles'],
            ['code' => '13130', 'description' => 'Finishing of textiles', 'category' => 'Textiles'],
            ['code' => '13910', 'description' => 'Manufacture of knitted and crocheted fabrics', 'category' => 'Textiles'],
            ['code' => '13921', 'description' => 'Manufacture of blankets, made-up furnishing articles and stuffed articles', 'category' => 'Textiles'],
            ['code' => '13922', 'description' => 'Manufacture of tents, tarpaulins, sails and other canvas goods and car seat covers', 'category' => 'Textiles'],
            ['code' => '13930', 'description' => 'Manufacture of carpets and rugs', 'category' => 'Textiles'],
            ['code' => '13940', 'description' => 'Manufacture of cordage, rope, twine, and netting', 'category' => 'Textiles'],
            ['code' => '13990', 'description' => 'Manufacture of other textiles n.e.c.', 'category' => 'Textiles'],
            ['code' => '14100', 'description' => 'Manufacturing of wearing apparel, except fur apparel', 'category' => 'Clothing'],
            ['code' => '14200', 'description' => 'Manufacture of articles of fur', 'category' => 'Clothing'],
            ['code' => '14300', 'description' => 'Manufacture of knitted and crocheted apparel', 'category' => 'Clothing'],

            // Leather and Related Products
            ['code' => '15110', 'description' => 'Tanning and dressing of leather; dressing and dyeing of fur', 'category' => 'Leather'],
            ['code' => '15120', 'description' => 'Manufacture of luggage, handbags and the like, saddlery, and harness', 'category' => 'Leather'],
            ['code' => '15200', 'description' => 'Manufacture of footwear', 'category' => 'Leather'],

            // Wood and Wood Products
            ['code' => '16100', 'description' => 'Sawmilling and planing of wood', 'category' => 'Wood Products'],
            ['code' => '16210', 'description' => 'Manufacture of veneer sheets and wood-based panels', 'category' => 'Wood Products'],
            ['code' => '16220', 'description' => 'Manufacture of builders\' carpentry and joinery', 'category' => 'Wood Products'],
            ['code' => '16230', 'description' => 'Manufacture of wooden containers', 'category' => 'Wood Products'],
            ['code' => '16291', 'description' => 'Manufacture of other products of wood', 'category' => 'Wood Products'],
            ['code' => '16292', 'description' => 'Manufacturing of other articles of cork, straw and plaiting materials, including', 'category' => 'Wood Products'],

            // Paper Products
            ['code' => '17010', 'description' => 'Manufacture of pulp, paper, and paperboard', 'category' => 'Paper Products'],
            ['code' => '17021', 'description' => 'Manufacture of corrugated paper and paperboard', 'category' => 'Paper Products'],
            ['code' => '17022', 'description' => 'Manufacture of containers of paper and paperboard', 'category' => 'Paper Products'],
            ['code' => '17090', 'description' => 'Manufacture of other articles of paper and paperboard', 'category' => 'Paper Products'],

            // Printing and Media
            ['code' => '18110', 'description' => 'Printing', 'category' => 'Printing'],
            ['code' => '18120', 'description' => 'Service activities related to printing', 'category' => 'Printing'],
            ['code' => '18200', 'description' => 'Reproduction of recorded media', 'category' => 'Printing'],

            // Petroleum Products
            ['code' => '19100', 'description' => 'Manufacture of coke oven products', 'category' => 'Petroleum Products'],
            ['code' => '19200', 'description' => 'Manufacture of refined petroleum products', 'category' => 'Petroleum Products'],

            // Chemical Products
            ['code' => '20110', 'description' => 'Manufacture of basic chemicals', 'category' => 'Chemicals'],
            ['code' => '20120', 'description' => 'Manufacture of fertilizers and nitrogen compounds', 'category' => 'Chemicals'],
            ['code' => '20130', 'description' => 'Manufacture of plastics and synthetic rubber in primary forms', 'category' => 'Chemicals'],
            ['code' => '20210', 'description' => 'Manufacture of pesticides and other agrochemical products', 'category' => 'Chemicals'],
            ['code' => '20220', 'description' => 'Manufacture of paints, varnishes and similar coatings, printing ink and mastics', 'category' => 'Chemicals'],
            ['code' => '20230', 'description' => 'Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations', 'category' => 'Chemicals'],
            ['code' => '20291', 'description' => 'Manufacture of explosives and pyrotechnic products', 'category' => 'Chemicals'],
            ['code' => '20292', 'description' => 'Manufacture of adhesives, glues, sizes, and cements', 'category' => 'Chemicals'],
            ['code' => '20299', 'description' => 'Manufacture of other chemical products n.e.c.', 'category' => 'Chemicals'],
            ['code' => '20300', 'description' => 'Manufacture of man-made fibres', 'category' => 'Chemicals'],
            ['code' => '21000', 'description' => 'Manufacture of pharmaceuticals, medicinal chemical, and botanical products', 'category' => 'Pharmaceuticals'],

            // Rubber and Plastic Products
            ['code' => '22110', 'description' => 'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres', 'category' => 'Rubber and Plastics'],
            ['code' => '22190', 'description' => 'Manufacture of other rubber products', 'category' => 'Rubber and Plastics'],
            ['code' => '22200', 'description' => 'Manufacture of plastic products', 'category' => 'Rubber and Plastics'],

            // Non-metallic Mineral Products
            ['code' => '23100', 'description' => 'Manufacture of glass and glass products', 'category' => 'Non-metallic Minerals'],
            ['code' => '23910', 'description' => 'Manufacture of refractory products', 'category' => 'Non-metallic Minerals'],
            ['code' => '23920', 'description' => 'Manufacture of clay building materials', 'category' => 'Non-metallic Minerals'],
            ['code' => '23930', 'description' => 'Manufacture of other porcelain and ceramic products', 'category' => 'Non-metallic Minerals'],
            ['code' => '23940', 'description' => 'Manufacture of cement, lime, and plaster', 'category' => 'Non-metallic Minerals'],
            ['code' => '23950', 'description' => 'Manufacture of articles of concrete, cement, and plaster', 'category' => 'Non-metallic Minerals'],
            ['code' => '23960', 'description' => 'Cutting, shaping, and finishing of stone', 'category' => 'Non-metallic Minerals'],
            ['code' => '23990', 'description' => 'Manufacture of other non-metallic mineral products n.e.c.', 'category' => 'Non-metallic Minerals'],

            // Basic Metals
            ['code' => '24101', 'description' => 'Basic iron and steel industries; except steel pipe and tube mills', 'category' => 'Basic Metals'],
            ['code' => '24102', 'description' => 'Steel pipe and tube mills', 'category' => 'Basic Metals'],
            ['code' => '24201', 'description' => 'Refining of precious metals, e.g. gold, silver, and platinum', 'category' => 'Basic Metals'],
            ['code' => '24202', 'description' => 'Manufacture of primary non-ferrous metal products, excluding precious metals', 'category' => 'Basic Metals'],
            ['code' => '24310', 'description' => 'Casting of iron and steel', 'category' => 'Basic Metals'],
            ['code' => '24320', 'description' => 'Casting of non-ferrous metals', 'category' => 'Basic Metals'],

            // Fabricated Metal Products
            ['code' => '25111', 'description' => 'Manufacture of metal structures or parts thereof', 'category' => 'Metal Products'],
            ['code' => '25119', 'description' => 'Manufacture of other structural metal products, e.g. metal doors, windows, and gates', 'category' => 'Metal Products'],
            ['code' => '25120', 'description' => 'Manufacture of tanks, reservoirs, and containers of metal', 'category' => 'Metal Products'],
            ['code' => '25130', 'description' => 'Manufacture of steam generators, except central heating hot water boilers', 'category' => 'Metal Products'],
            ['code' => '25200', 'description' => 'Manufacture of weapons and ammunition', 'category' => 'Metal Products'],
            ['code' => '25910', 'description' => 'Forging, pressing, stamping, and roll-forming of metal; powder metallurgy', 'category' => 'Metal Products'],
            ['code' => '25921', 'description' => 'Treating and coating of metals', 'category' => 'Metal Products'],
            ['code' => '25922', 'description' => 'General mechanical engineering on a fee or contract basis', 'category' => 'Metal Products'],
            ['code' => '25930', 'description' => 'Manufacture of cutlery, hand tools and general hardware', 'category' => 'Metal Products'],
            ['code' => '25991', 'description' => 'Manufacture of metal containers, e.g. cans and tins', 'category' => 'Metal Products'],
            ['code' => '25992', 'description' => 'Manufacture of cables and wire products', 'category' => 'Metal Products'],
            ['code' => '25993', 'description' => 'Manufacture of springs (all types)', 'category' => 'Metal Products'],
            ['code' => '25994', 'description' => 'Manufacture of metal fasteners', 'category' => 'Metal Products'],
            ['code' => '25999', 'description' => 'Other Manufacture of other fabricated metal products n.e.c.', 'category' => 'Metal Products'],

            // Computer, Electronic and Optical Products
            ['code' => '26100', 'description' => 'Manufacture of electronic components and boards', 'category' => 'Electronics'],
            ['code' => '26200', 'description' => 'Manufacture of computers and peripheral equipment', 'category' => 'Electronics'],
            ['code' => '26300', 'description' => 'Manufacture of communication equipment', 'category' => 'Electronics'],
            ['code' => '26400', 'description' => 'Manufacture of consumer electronics', 'category' => 'Electronics'],
            ['code' => '26510', 'description' => 'Manufacture of measuring, testing, navigating and control equipment', 'category' => 'Electronics'],
            ['code' => '26520', 'description' => 'Manufacture of watches and clocks', 'category' => 'Electronics'],
            ['code' => '26600', 'description' => 'Manufacture of irradiation, electromedical and electrotherapeutic equipment', 'category' => 'Electronics'],
            ['code' => '26700', 'description' => 'Manufacture of optical instruments and photographic equipment', 'category' => 'Electronics'],
            ['code' => '26800', 'description' => 'Manufacture of magnetic and optical media', 'category' => 'Electronics'],

            // Electrical Equipment
            ['code' => '27100', 'description' => 'Manufacture of electric motors, generators, transformers, and electricity distribution and control apparatus', 'category' => 'Electrical Equipment'],
            ['code' => '27200', 'description' => 'Manufacture of batteries and accumulators', 'category' => 'Electrical Equipment'],
            ['code' => '27310', 'description' => 'Manufacture of fibre optic cables', 'category' => 'Electrical Equipment'],
            ['code' => '27320', 'description' => 'Manufacture of other electronic and electric wires and cables', 'category' => 'Electrical Equipment'],
            ['code' => '27330', 'description' => 'Manufacture of wiring devices', 'category' => 'Electrical Equipment'],
            ['code' => '27400', 'description' => 'Manufacture of electric lighting equipment', 'category' => 'Electrical Equipment'],
            ['code' => '27500', 'description' => 'Manufacture of domestic appliances', 'category' => 'Electrical Equipment'],
            ['code' => '27900', 'description' => 'Manufacture of other electrical equipment', 'category' => 'Electrical Equipment'],

            // Machinery and Equipment
            ['code' => '28110', 'description' => 'Manufacture of engines and turbines, except aircraft, vehicle, and cycle engines', 'category' => 'Machinery'],
            ['code' => '28120', 'description' => 'Manufacture of fluid power equipment', 'category' => 'Machinery'],
            ['code' => '28130', 'description' => 'Manufacture of other pumps, compressors, taps and valves', 'category' => 'Machinery'],
            ['code' => '28140', 'description' => 'Manufacture of bearings, gears, gearing and driving elements', 'category' => 'Machinery'],
            ['code' => '28150', 'description' => 'Manufacture of ovens, furnaces, and furnace burners', 'category' => 'Machinery'],
            ['code' => '28160', 'description' => 'Manufacture of lifting and handling equipment', 'category' => 'Machinery'],
            ['code' => '28170', 'description' => 'Manufacture of office machinery and equipment (except computers and peripheral equipment)', 'category' => 'Machinery'],
            ['code' => '28180', 'description' => 'Manufacture of power-driven hand tools', 'category' => 'Machinery'],
            ['code' => '28190', 'description' => 'Manufacture of other general-purpose machinery', 'category' => 'Machinery'],
            ['code' => '28210', 'description' => 'Manufacture of agricultural and forestry machinery', 'category' => 'Machinery'],
            ['code' => '28220', 'description' => 'Manufacture of metal-forming machinery and machine tools', 'category' => 'Machinery'],
            ['code' => '28230', 'description' => 'Manufacture of machinery for metallurgy', 'category' => 'Machinery'],
            ['code' => '28240', 'description' => 'Manufacture of machinery for mining, quarrying and construction', 'category' => 'Machinery'],
            ['code' => '28250', 'description' => 'Manufacture of machinery for food, beverage, and tobacco processing', 'category' => 'Machinery'],
            ['code' => '28260', 'description' => 'Manufacture of machinery for textile, apparel, and leather production', 'category' => 'Machinery'],
            ['code' => '28290', 'description' => 'Manufacture of other special-purpose machinery', 'category' => 'Machinery'],

            // Motor Vehicles and Transport Equipment
            ['code' => '29100', 'description' => 'Manufacture of motor vehicles', 'category' => 'Transport Equipment'],
            ['code' => '29200', 'description' => 'Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers', 'category' => 'Transport Equipment'],
            ['code' => '29300', 'description' => 'Manufacture of parts and accessories for motor vehicles', 'category' => 'Transport Equipment'],
            ['code' => '30110', 'description' => 'Building of ships and floating structures', 'category' => 'Transport Equipment'],
            ['code' => '30120', 'description' => 'Building of pleasure and sporting boats', 'category' => 'Transport Equipment'],
            ['code' => '30200', 'description' => 'Manufacture of railway locomotives and rolling stock', 'category' => 'Transport Equipment'],
            ['code' => '30300', 'description' => 'Manufacture of air and spacecraft and related machinery', 'category' => 'Transport Equipment'],
            ['code' => '30400', 'description' => 'Manufacture of military fighting vehicles', 'category' => 'Transport Equipment'],
            ['code' => '30910', 'description' => 'Manufacture of motorcycles', 'category' => 'Transport Equipment'],
            ['code' => '30920', 'description' => 'Manufacture of bicycles and invalid carriages', 'category' => 'Transport Equipment'],
            ['code' => '30990', 'description' => 'Manufacture of other transport equipment n.e.c.', 'category' => 'Transport Equipment'],

            // Furniture and Other Manufacturing
            ['code' => '31000', 'description' => 'Manufacture of furniture', 'category' => 'Furniture'],
            ['code' => '32111', 'description' => 'Manufacture of jewellery and related articles composed of precious metals, precious and semi-precious stone and pearls', 'category' => 'Other Manufacturing'],
            ['code' => '32119', 'description' => 'Other precious and semi-precious stone cutting and polishing', 'category' => 'Other Manufacturing'],
            ['code' => '32120', 'description' => 'Manufacture of imitation jewellery and related articles', 'category' => 'Other Manufacturing'],
            ['code' => '32200', 'description' => 'Manufacture of musical instruments', 'category' => 'Other Manufacturing'],
            ['code' => '32300', 'description' => 'Manufacture of sports goods', 'category' => 'Other Manufacturing'],
            ['code' => '32400', 'description' => 'Manufacture of games and toys', 'category' => 'Other Manufacturing'],
            ['code' => '32500', 'description' => 'Manufacture of medical and dental instruments and supplies', 'category' => 'Other Manufacturing'],
            ['code' => '32901', 'description' => 'Manufacture of coffins', 'category' => 'Other Manufacturing'],
            ['code' => '32909', 'description' => 'Other manufacture n.e.c. (except coffins)', 'category' => 'Other Manufacturing'],

            // Repair and Installation
            ['code' => '33110', 'description' => 'Repair of fabricated metal products', 'category' => 'Repair Services'],
            ['code' => '33120', 'description' => 'Repair of machinery', 'category' => 'Repair Services'],
            ['code' => '33130', 'description' => 'Repair of electronic and optical equipment', 'category' => 'Repair Services'],
            ['code' => '33140', 'description' => 'Repair of electrical equipment', 'category' => 'Repair Services'],
            ['code' => '33150', 'description' => 'Repair of transport equipment, except motor vehicles', 'category' => 'Repair Services'],
            ['code' => '33190', 'description' => 'Repair of other equipment', 'category' => 'Repair Services'],
            ['code' => '33200', 'description' => 'Installation of industrial machinery and equipment', 'category' => 'Installation Services'],

            // Electricity, Gas, Steam and Air Conditioning
            ['code' => '35101', 'description' => 'Generation of electricity', 'category' => 'Utilities'],
            ['code' => '35102', 'description' => 'Distribution of purchased electric energy only', 'category' => 'Utilities'],
            ['code' => '35103', 'description' => 'Generation and/or distribution for own use', 'category' => 'Utilities'],
            ['code' => '35200', 'description' => 'Manufacture of gas; distribution of gaseous fuels through mains', 'category' => 'Utilities'],
            ['code' => '35300', 'description' => 'Steam and air conditioning supply', 'category' => 'Utilities'],

            // Water Supply and Waste Management
            ['code' => '36000', 'description' => 'Water collection, treatment, and supply', 'category' => 'Water and Waste'],
            ['code' => '37000', 'description' => 'Sewerage', 'category' => 'Water and Waste'],
            ['code' => '38110', 'description' => 'Collection of non-hazardous waste', 'category' => 'Water and Waste'],
            ['code' => '38120', 'description' => 'Collection of hazardous waste', 'category' => 'Water and Waste'],
            ['code' => '38210', 'description' => 'Treatment and disposal of non-hazardous waste', 'category' => 'Water and Waste'],
            ['code' => '38220', 'description' => 'Treatment and disposal of hazardous waste', 'category' => 'Water and Waste'],
            ['code' => '38300', 'description' => 'Materials recovery', 'category' => 'Water and Waste'],
            ['code' => '39000', 'description' => 'Remediation activities and other waste management services', 'category' => 'Water and Waste'],

            // Construction
            ['code' => '41000', 'description' => 'Construction of buildings', 'category' => 'Construction'],
            ['code' => '42100', 'description' => 'Construction of roads and railways', 'category' => 'Construction'],
            ['code' => '42200', 'description' => 'Construction of utility projects', 'category' => 'Construction'],
            ['code' => '42900', 'description' => 'Construction of other civil engineering projects', 'category' => 'Construction'],
            ['code' => '43110', 'description' => 'Demolition', 'category' => 'Construction'],
            ['code' => '43120', 'description' => 'Site preparation', 'category' => 'Construction'],
            ['code' => '43210', 'description' => 'Electrical installation', 'category' => 'Construction'],
            ['code' => '43220', 'description' => 'Plumbing, heat, and air-conditioning installation', 'category' => 'Construction'],
            ['code' => '43290', 'description' => 'Other construction installation', 'category' => 'Construction'],
            ['code' => '43301', 'description' => 'Painting and decorating', 'category' => 'Construction'],
            ['code' => '43302', 'description' => 'Shop fitting', 'category' => 'Construction'],
            ['code' => '43309', 'description' => 'Other building and completion and finishing', 'category' => 'Construction'],
            ['code' => '43901', 'description' => 'Rental of construction machinery and equipment (with operator)', 'category' => 'Construction'],
            ['code' => '43909', 'description' => 'Other specialized construction activities n.e.c.', 'category' => 'Construction'],

            // Wholesale and Retail Trade - Motor Vehicles
            ['code' => '45101', 'description' => 'Wholesale of motor vehicles', 'category' => 'Motor Vehicle Trade'],
            ['code' => '45102', 'description' => 'Retail of new motor vehicles', 'category' => 'Motor Vehicle Trade'],
            ['code' => '45103', 'description' => 'Retail sale of used motor vehicles', 'category' => 'Motor Vehicle Trade'],
            ['code' => '45200', 'description' => 'Maintenance and repair of motor vehicles', 'category' => 'Motor Vehicle Trade'],
            ['code' => '45300', 'description' => 'Sale of motor vehicle parts and accessories', 'category' => 'Motor Vehicle Trade'],
            ['code' => '45400', 'description' => 'Sale, maintenance and repair of motorcycles and related parts and accessories', 'category' => 'Motor Vehicle Trade'],
            ['code' => '45500', 'description' => 'Retail of automotive fuel in specialized stores', 'category' => 'Motor Vehicle Trade'],

            // Wholesale Trade
            ['code' => '46100', 'description' => 'Wholesale on a fee or contract basis', 'category' => 'Wholesale Trade'],
            ['code' => '46200', 'description' => 'Wholesale of agricultural raw materials and live animals', 'category' => 'Wholesale Trade'],
            ['code' => '46301', 'description' => 'Wholesale trade in foodstuffs', 'category' => 'Wholesale Trade'],
            ['code' => '46302', 'description' => 'Wholesale trade in beverages', 'category' => 'Wholesale Trade'],
            ['code' => '46303', 'description' => 'Wholesale in tobacco products', 'category' => 'Wholesale Trade'],
            ['code' => '46410', 'description' => 'Wholesale of textiles, clothing, and footwear', 'category' => 'Wholesale Trade'],
            ['code' => '46491', 'description' => 'Wholesale trade in household furniture, requisites, and appliances', 'category' => 'Wholesale Trade'],
            ['code' => '46492', 'description' => 'Wholesale trade in books and stationery', 'category' => 'Wholesale Trade'],
            ['code' => '46493', 'description' => 'Wholesale trade in pharmaceuticals, toiletries, and medical equipment', 'category' => 'Wholesale Trade'],
            ['code' => '46499', 'description' => 'Other wholesale trade in other household goods n.e.c.', 'category' => 'Wholesale Trade'],
            ['code' => '46510', 'description' => 'Wholesale of computers, computer peripheral equipment and software', 'category' => 'Wholesale Trade'],
            ['code' => '46520', 'description' => 'Wholesale of electronic and telecommunications equipment and parts', 'category' => 'Wholesale Trade'],
            ['code' => '46530', 'description' => 'Wholesale of agricultural machinery, equipment, and supplies', 'category' => 'Wholesale Trade'],
            ['code' => '46590', 'description' => 'Wholesale of other machinery and equipment', 'category' => 'Wholesale Trade'],
            ['code' => '46610', 'description' => 'Wholesale of solid, liquid, and gaseous fuels and related products', 'category' => 'Wholesale Trade'],
            ['code' => '46621', 'description' => 'Wholesale of gold', 'category' => 'Wholesale Trade'],
            ['code' => '46629', 'description' => 'Other wholesale of metals and metal ores', 'category' => 'Wholesale Trade'],
            ['code' => '46630', 'description' => 'Wholesale of construction materials, hardware, plumbing and heating equipment and supplies', 'category' => 'Wholesale Trade'],
            ['code' => '46691', 'description' => 'Sale of used parts and accessories, including scrapyards', 'category' => 'Wholesale Trade'],
            ['code' => '46692', 'description' => 'Wholesale trade in diamonds, pearls, and other precious and semi-precious stones', 'category' => 'Wholesale Trade'],
            ['code' => '46699', 'description' => 'Other wholesale of waste and scrap and other products n.e.c.', 'category' => 'Wholesale Trade'],
            ['code' => '46900', 'description' => 'Non-specialised wholesale trade', 'category' => 'Wholesale Trade'],

            // Retail Trade
            ['code' => '47110', 'description' => 'Retail sale in non-specialized stores with food, beverages or tobacco predominating', 'category' => 'Retail Trade'],
            ['code' => '47190', 'description' => 'Other retail sale in non-specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47211', 'description' => 'Retail trade in fresh fruit and vegetables', 'category' => 'Retail Trade'],
            ['code' => '47212', 'description' => 'Retail in meat and meat products', 'category' => 'Retail Trade'],
            ['code' => '47213', 'description' => 'Retail trade in bakery products', 'category' => 'Retail Trade'],
            ['code' => '47219', 'description' => 'Other retail sale in specialised stores', 'category' => 'Retail Trade'],
            ['code' => '47220', 'description' => 'Retail sale of beverages in specialised stores', 'category' => 'Retail Trade'],
            ['code' => '47230', 'description' => 'Retail sale of tobacco products in specialised stores', 'category' => 'Retail Trade'],
            ['code' => '47310', 'description' => 'Retail sale of computers, peripheral units, software, and telecommunications', 'category' => 'Retail Trade'],
            ['code' => '47320', 'description' => 'Retail sale of audio and video equipment in specialised stores', 'category' => 'Retail Trade'],
            ['code' => '47410', 'description' => 'Retail sale of textiles in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47420', 'description' => 'Retail sale of hardware, paints, and glass in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47430', 'description' => 'Retail sale of carpets, rugs, wall, and floor coverings in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47490', 'description' => 'Retail sale of electrical household appliances, furniture, lighting equipment and other household articles in specialised stores', 'category' => 'Retail Trade'],
            ['code' => '47510', 'description' => 'Retail sale of books, newspapers, and stationery in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47520', 'description' => 'Retail sale of music and video recordings in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47530', 'description' => 'Retail sale of sporting equipment in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47540', 'description' => 'Retail sale of games and toys in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47610', 'description' => 'Retail sale of clothing, footwear, and leather articles in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47620', 'description' => 'Retail sale of pharmaceutical and medical goods, cosmetic and toilet articles in specialized stores', 'category' => 'Retail Trade'],
            ['code' => '47631', 'description' => 'Specialized retail sale of jewellery', 'category' => 'Retail Trade'],
            ['code' => '47632', 'description' => 'Specialized retail sale of watches and clocks', 'category' => 'Retail Trade'],
            ['code' => '47639', 'description' => 'Other retail sale of new goods in specialized stores n.e.c.', 'category' => 'Retail Trade'],
            ['code' => '47640', 'description' => 'Retail sale of second-hand goods', 'category' => 'Retail Trade'],
            ['code' => '47710', 'description' => 'Retail sale via stalls and markets of food, beverages, and tobacco products', 'category' => 'Retail Trade'],
            ['code' => '47720', 'description' => 'Retail sale via stalls and markets of textiles, clothing, and footwear', 'category' => 'Retail Trade'],
            ['code' => '47790', 'description' => 'Retail sale via stalls and markets of other goods', 'category' => 'Retail Trade'],
            ['code' => '47810', 'description' => 'Retail sale via mail order houses or via internet', 'category' => 'Retail Trade'],
            ['code' => '47890', 'description' => 'Other retail sale not in stores, stalls, or markets', 'category' => 'Retail Trade'],

            // Transportation and Storage
            ['code' => '49110', 'description' => 'Passenger rail transport, interurban', 'category' => 'Transportation'],
            ['code' => '49120', 'description' => 'Freight rail transport', 'category' => 'Transportation'],
            ['code' => '49210', 'description' => 'Urban and suburban passenger transport', 'category' => 'Transportation'],
            ['code' => '49221', 'description' => 'Minibus Taxi transport', 'category' => 'Transportation'],
            ['code' => '49222', 'description' => 'Other Taxi transport (except minibus taxis)', 'category' => 'Transportation'],
            ['code' => '49223', 'description' => 'Bus transport', 'category' => 'Transportation'],
            ['code' => '49229', 'description' => 'Other passenger land transport n.e.c.', 'category' => 'Transportation'],
            ['code' => '49230', 'description' => 'Freight transport by road', 'category' => 'Transportation'],
            ['code' => '49300', 'description' => 'Transport via pipeline', 'category' => 'Transportation'],
            ['code' => '50110', 'description' => 'Sea and coastal passenger water transport', 'category' => 'Transportation'],
            ['code' => '50120', 'description' => 'Sea and coastal freight water transport', 'category' => 'Transportation'],
            ['code' => '50210', 'description' => 'Inland passenger water transport', 'category' => 'Transportation'],
            ['code' => '50220', 'description' => 'Inland freight water transport', 'category' => 'Transportation'],
            ['code' => '51100', 'description' => 'Passenger air transport', 'category' => 'Transportation'],
            ['code' => '51200', 'description' => 'Freight air transport', 'category' => 'Transportation'],
            ['code' => '52100', 'description' => 'Warehousing and storage', 'category' => 'Transportation'],
            ['code' => '52211', 'description' => 'Operation of parking garages and parking lots', 'category' => 'Transportation'],
            ['code' => '52212', 'description' => 'Operation of roads and toll roads', 'category' => 'Transportation'],
            ['code' => '52219', 'description' => 'Other service activities incidental to land transportation', 'category' => 'Transportation'],
            ['code' => '52220', 'description' => 'Service activities incidental to water transportation', 'category' => 'Transportation'],
            ['code' => '52230', 'description' => 'Service activities incidental to air transportation', 'category' => 'Transportation'],
            ['code' => '52240', 'description' => 'Cargo handling', 'category' => 'Transportation'],
            ['code' => '52290', 'description' => 'Other transportation support activities', 'category' => 'Transportation'],

            // Postal and Courier Activities
            ['code' => '53100', 'description' => 'Postal activities', 'category' => 'Postal Services'],
            ['code' => '53200', 'description' => 'Courier activities', 'category' => 'Postal Services'],

            // Accommodation and Food Service Activities
            ['code' => '55101', 'description' => 'Short term accommodation activities of hotels and motels', 'category' => 'Accommodation'],
            ['code' => '55102', 'description' => 'Short term accommodation activities of guesthouses, bed, and breakfast', 'category' => 'Accommodation'],
            ['code' => '55103', 'description' => 'Short term accommodation activities of pensions, youth hostels and mountain refuges', 'category' => 'Accommodation'],
            ['code' => '55109', 'description' => 'Short term accommodation activities of visitor flats and bungalows, time-share units and holiday homes and other accommodation', 'category' => 'Accommodation'],
            ['code' => '55200', 'description' => 'Camping grounds, recreational vehicle parks and trailer parks', 'category' => 'Accommodation'],
            ['code' => '55900', 'description' => 'Other accommodation', 'category' => 'Accommodation'],
            ['code' => '56101', 'description' => 'Food service activities of take away counters', 'category' => 'Food Services'],
            ['code' => '56109', 'description' => 'Other restaurant and mobile food service activities', 'category' => 'Food Services'],
            ['code' => '56210', 'description' => 'Event catering', 'category' => 'Food Services'],
            ['code' => '56290', 'description' => 'Other food service activities', 'category' => 'Food Services'],
            ['code' => '56300', 'description' => 'Beverage serving activities', 'category' => 'Food Services'],

            // Information and Communication
            ['code' => '58110', 'description' => 'Book publishing', 'category' => 'Publishing'],
            ['code' => '58120', 'description' => 'Publishing of directories and mailing lists', 'category' => 'Publishing'],
            ['code' => '58130', 'description' => 'Publishing of newspapers, journals, and periodicals', 'category' => 'Publishing'],
            ['code' => '58190', 'description' => 'Other publishing activities', 'category' => 'Publishing'],
            ['code' => '58200', 'description' => 'Software publishing', 'category' => 'Publishing'],
            ['code' => '59110', 'description' => 'Motion picture, video, and television programme production activities', 'category' => 'Media'],
            ['code' => '59120', 'description' => 'Motion picture, video, and television programme post-production activities', 'category' => 'Media'],
            ['code' => '59130', 'description' => 'Motion picture, video, and television programme distribution activities', 'category' => 'Media'],
            ['code' => '59140', 'description' => 'Motion picture projection activities', 'category' => 'Media'],
            ['code' => '59200', 'description' => 'Sound recording and music publishing activities', 'category' => 'Media'],
            ['code' => '60100', 'description' => 'Radio broadcasting', 'category' => 'Broadcasting'],
            ['code' => '60200', 'description' => 'Television programming and broadcasting activities', 'category' => 'Broadcasting'],
            ['code' => '61100', 'description' => 'Wired telecommunications activities', 'category' => 'Telecommunications'],
            ['code' => '61200', 'description' => 'Wireless telecommunications activities', 'category' => 'Telecommunications'],
            ['code' => '61300', 'description' => 'Satellite telecommunications activities', 'category' => 'Telecommunications'],
            ['code' => '61900', 'description' => 'Other telecommunications activities', 'category' => 'Telecommunications'],
            ['code' => '62010', 'description' => 'Computer programming activities', 'category' => 'IT Services'],
            ['code' => '62020', 'description' => 'Computer consultancy and computer facilities management activities', 'category' => 'IT Services'],
            ['code' => '62090', 'description' => 'Other information technology and computer service activities', 'category' => 'IT Services'],
            ['code' => '63110', 'description' => 'Data processing, hosting, and related activities', 'category' => 'IT Services'],
            ['code' => '63120', 'description' => 'Web portals', 'category' => 'IT Services'],
            ['code' => '63910', 'description' => 'News agency activities', 'category' => 'Information Services'],
            ['code' => '63990', 'description' => 'Other information service activities n.e.c.', 'category' => 'Information Services'],

            // Financial and Insurance Activities
            ['code' => '64110', 'description' => 'Central banking', 'category' => 'Financial Services'],
            ['code' => '64190', 'description' => 'Other monetary intermediation', 'category' => 'Financial Services'],
            ['code' => '64200', 'description' => 'Activities of holding companies', 'category' => 'Financial Services'],
            ['code' => '64300', 'description' => 'Trusts, funds, and similar financial entities', 'category' => 'Financial Services'],
            ['code' => '64910', 'description' => 'Financial leasing', 'category' => 'Financial Services'],
            ['code' => '64920', 'description' => 'Other credit granting', 'category' => 'Financial Services'],
            ['code' => '64990', 'description' => 'Other financial service activities, except insurance and pension funding activities n.e.c.', 'category' => 'Financial Services'],
            ['code' => '65110', 'description' => 'Life insurance', 'category' => 'Insurance'],
            ['code' => '65121', 'description' => 'Health insurance', 'category' => 'Insurance'],
            ['code' => '65122', 'description' => 'Travel insurance', 'category' => 'Insurance'],
            ['code' => '65123', 'description' => 'Transport insurance', 'category' => 'Insurance'],
            ['code' => '65129', 'description' => 'Other non-life insurance', 'category' => 'Insurance'],
            ['code' => '65200', 'description' => 'Reinsurance', 'category' => 'Insurance'],
            ['code' => '65300', 'description' => 'Pension funding', 'category' => 'Insurance'],
            ['code' => '66110', 'description' => 'Administration of financial markets', 'category' => 'Financial Services'],
            ['code' => '66120', 'description' => 'Security and commodity contracts brokerage', 'category' => 'Financial Services'],
            ['code' => '66190', 'description' => 'Other activities auxiliary to financial service activities', 'category' => 'Financial Services'],
            ['code' => '66210', 'description' => 'Risk and damage evaluation', 'category' => 'Insurance'],
            ['code' => '66220', 'description' => 'Activities of insurance agents and brokers', 'category' => 'Insurance'],
            ['code' => '66290', 'description' => 'Other activities auxiliary to insurance and pension funding', 'category' => 'Insurance'],
            ['code' => '66300', 'description' => 'Fund management activities', 'category' => 'Financial Services'],

            // Real Estate Activities
            ['code' => '68100', 'description' => 'Real estate activities with own or leased property', 'category' => 'Real Estate'],
            ['code' => '68200', 'description' => 'Real estate activities on a fee or contract basis', 'category' => 'Real Estate'],

            // Professional, Scientific and Technical Activities
            ['code' => '69100', 'description' => 'Legal activities', 'category' => 'Professional Services'],
            ['code' => '69201', 'description' => 'Accounting and bookkeeping activities', 'category' => 'Professional Services'],
            ['code' => '69202', 'description' => 'Auditing activities', 'category' => 'Professional Services'],
            ['code' => '69209', 'description' => 'Other accounting, bookkeeping, and auditing activities, tax consultancy', 'category' => 'Professional Services'],
            ['code' => '70100', 'description' => 'Activities of head offices', 'category' => 'Management Services'],
            ['code' => '70200', 'description' => 'Management consultancy activities', 'category' => 'Management Services'],
            ['code' => '71101', 'description' => 'Consulting engineering activities', 'category' => 'Technical Services'],
            ['code' => '71102', 'description' => 'Architectural activities', 'category' => 'Technical Services'],
            ['code' => '71103', 'description' => 'Activities of quantity surveyors', 'category' => 'Technical Services'],
            ['code' => '71104', 'description' => 'Activities of land surveyors', 'category' => 'Technical Services'],
            ['code' => '71105', 'description' => 'Geological and prospecting activities on a fee or contract basis', 'category' => 'Technical Services'],
            ['code' => '71106', 'description' => 'Activities of non-registered architects, e.g. tracers and draughtsmen', 'category' => 'Technical Services'],
            ['code' => '71109', 'description' => 'Other architectural and engineering activities and related technical consultancy', 'category' => 'Technical Services'],
            ['code' => '71200', 'description' => 'Technical testing and analysis', 'category' => 'Technical Services'],
            ['code' => '72100', 'description' => 'Research and experimental development on natural sciences and engineering', 'category' => 'Research Services'],
            ['code' => '72200', 'description' => 'Research and experimental development on social sciences and humanities', 'category' => 'Research Services'],
            ['code' => '73100', 'description' => 'Advertising', 'category' => 'Marketing Services'],
            ['code' => '73200', 'description' => 'Market research and public opinion polling', 'category' => 'Marketing Services'],
            ['code' => '74100', 'description' => 'Specialized design activities', 'category' => 'Design Services'],
            ['code' => '74200', 'description' => 'Photographic activities', 'category' => 'Creative Services'],
            ['code' => '74900', 'description' => 'Other professional, scientific, and technical activities n.e.c.', 'category' => 'Professional Services'],
            ['code' => '75000', 'description' => 'Veterinary activities', 'category' => 'Veterinary Services'],

            // Administrative and Support Service Activities
            ['code' => '77100', 'description' => 'Renting and leasing of motor vehicles (without driver)', 'category' => 'Rental Services'],
            ['code' => '77210', 'description' => 'Renting and leasing of recreational and sports goods', 'category' => 'Rental Services'],
            ['code' => '77220', 'description' => 'Renting of video tapes and disks', 'category' => 'Rental Services'],
            ['code' => '77290', 'description' => 'Renting and leasing of other personal and household goods', 'category' => 'Rental Services'],
            ['code' => '77301', 'description' => 'Renting of land transport equipment', 'category' => 'Rental Services'],
            ['code' => '77302', 'description' => 'Renting of water transport equipment', 'category' => 'Rental Services'],
            ['code' => '77303', 'description' => 'Renting of air transport equipment', 'category' => 'Rental Services'],
            ['code' => '77304', 'description' => 'Renting of agricultural machinery and equipment', 'category' => 'Rental Services'],
            ['code' => '77305', 'description' => 'Renting of construction and civil engineering machinery and equipment', 'category' => 'Rental Services'],
            ['code' => '77306', 'description' => 'Renting of office machinery and equipment', 'category' => 'Rental Services'],
            ['code' => '77309', 'description' => 'Renting and leasing of other machinery, equipment, and tangible goods n.e.c.', 'category' => 'Rental Services'],
            ['code' => '77400', 'description' => 'Leasing of intellectual property and similar products, except copyrighted works', 'category' => 'Rental Services'],
            ['code' => '78100', 'description' => 'Activities of employment placement agencies', 'category' => 'Employment Services'],
            ['code' => '78200', 'description' => 'Temporary employment agency activities', 'category' => 'Employment Services'],
            ['code' => '78300', 'description' => 'Other human resources provision', 'category' => 'Employment Services'],
            ['code' => '79110', 'description' => 'Travel agency activities', 'category' => 'Travel Services'],
            ['code' => '79120', 'description' => 'Tour operator activities', 'category' => 'Travel Services'],
            ['code' => '79900', 'description' => 'Other reservation service and related activities', 'category' => 'Travel Services'],
            ['code' => '80100', 'description' => 'Private security activities', 'category' => 'Security Services'],
            ['code' => '80200', 'description' => 'Security systems service activities', 'category' => 'Security Services'],
            ['code' => '80300', 'description' => 'Investigation activities', 'category' => 'Security Services'],
            ['code' => '81100', 'description' => 'Combined facilities support activities', 'category' => 'Facilities Services'],
            ['code' => '81210', 'description' => 'General cleaning of buildings', 'category' => 'Cleaning Services'],
            ['code' => '81290', 'description' => 'Other building and industrial cleaning activities', 'category' => 'Cleaning Services'],
            ['code' => '81300', 'description' => 'Landscape care and maintenance service activities', 'category' => 'Landscaping Services'],
            ['code' => '82110', 'description' => 'Combined office administrative service activities', 'category' => 'Administrative Services'],
            ['code' => '82190', 'description' => 'Photocopying, document preparation and other specialized office support activities', 'category' => 'Administrative Services'],
            ['code' => '82200', 'description' => 'Activities of call centres', 'category' => 'Administrative Services'],
            ['code' => '82300', 'description' => 'Organization of conventions and trade shows', 'category' => 'Event Services'],
            ['code' => '82910', 'description' => 'Activities of collection agencies and credit bureaus', 'category' => 'Business Support'],
            ['code' => '82920', 'description' => 'Packaging activities', 'category' => 'Business Support'],
            ['code' => '82990', 'description' => 'Other business support service activities n.e.c.', 'category' => 'Business Support'],

            // Public Administration and Defence
            ['code' => '84111', 'description' => 'General public administration at National Government level', 'category' => 'Public Administration'],
            ['code' => '84112', 'description' => 'General public administration at Provincial Government level', 'category' => 'Public Administration'],
            ['code' => '84113', 'description' => 'General public administration at Local Government level', 'category' => 'Public Administration'],
            ['code' => '84121', 'description' => 'Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security at National Government level', 'category' => 'Public Administration'],
            ['code' => '84122', 'description' => 'Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security at Provincial Government level', 'category' => 'Public Administration'],
            ['code' => '84123', 'description' => 'Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security at Local Government level', 'category' => 'Public Administration'],
            ['code' => '84131', 'description' => 'Regulation of and contribution to more efficient operation of businesses at National Government level', 'category' => 'Public Administration'],
            ['code' => '84132', 'description' => 'Regulation of and contribution to more efficient operation of businesses at Provincial Government level', 'category' => 'Public Administration'],
            ['code' => '84133', 'description' => 'Regulation of and contribution to more efficient operation of businesses at Local Government level', 'category' => 'Public Administration'],
            ['code' => '84140', 'description' => 'Extra budgetary account n.e.c.', 'category' => 'Public Administration'],
            ['code' => '84210', 'description' => 'Foreign affairs', 'category' => 'Public Administration'],
            ['code' => '84220', 'description' => 'Defence activities', 'category' => 'Defence'],
            ['code' => '84231', 'description' => 'Public order and safety activities at National Government level', 'category' => 'Public Safety'],
            ['code' => '84232', 'description' => 'Public order and safety activities at Provincial Government level', 'category' => 'Public Safety'],
            ['code' => '84233', 'description' => 'Public order and safety activities at Local Government level', 'category' => 'Public Safety'],
            ['code' => '84300', 'description' => 'Compulsory social security activities', 'category' => 'Social Security'],

            // Education
            ['code' => '85101', 'description' => 'Pre-primary education and activities of after-school centres', 'category' => 'Education'],
            ['code' => '85102', 'description' => 'Primary education', 'category' => 'Education'],
            ['code' => '85210', 'description' => 'General secondary education', 'category' => 'Education'],
            ['code' => '85220', 'description' => 'Technical and vocational secondary education', 'category' => 'Education'],
            ['code' => '85300', 'description' => 'Higher education', 'category' => 'Education'],
            ['code' => '85410', 'description' => 'Sports and recreation education', 'category' => 'Education'],
            ['code' => '85420', 'description' => 'Cultural education', 'category' => 'Education'],
            ['code' => '85490', 'description' => 'Other education n.e.c.', 'category' => 'Education'],
            ['code' => '85500', 'description' => 'Educational support activities', 'category' => 'Education'],

            // Human Health and Social Work Activities
            ['code' => '86100', 'description' => 'Hospital activities', 'category' => 'Healthcare'],
            ['code' => '86201', 'description' => 'Medical practitioner- and specialist activities', 'category' => 'Healthcare'],
            ['code' => '86202', 'description' => 'Dentist and specialist dentist activities', 'category' => 'Healthcare'],
            ['code' => '86209', 'description' => 'Other medical and dental practice activities', 'category' => 'Healthcare'],
            ['code' => '86900', 'description' => 'Other human health activities', 'category' => 'Healthcare'],
            ['code' => '87100', 'description' => 'Residential nursing care facilities', 'category' => 'Social Work'],
            ['code' => '87200', 'description' => 'Residential care activities for mental retardation, mental health, and substance abuse', 'category' => 'Social Work'],
            ['code' => '87300', 'description' => 'Residential care activities for the elderly and disabled', 'category' => 'Social Work'],
            ['code' => '87900', 'description' => 'Other residential care activities', 'category' => 'Social Work'],
            ['code' => '88100', 'description' => 'Social work activities without accommodation for the elderly and disabled', 'category' => 'Social Work'],
            ['code' => '88900', 'description' => 'Other social work activities without accommodation', 'category' => 'Social Work'],

            // Arts, Entertainment and Recreation
            ['code' => '90000', 'description' => 'Creative, arts and entertainment activities', 'category' => 'Arts and Entertainment'],
            ['code' => '91010', 'description' => 'Library and archives activities', 'category' => 'Arts and Entertainment'],
            ['code' => '91020', 'description' => 'Museums activities and operation of historical sites and buildings', 'category' => 'Arts and Entertainment'],
            ['code' => '91030', 'description' => 'Botanical and zoological gardens and nature reserves activities', 'category' => 'Arts and Entertainment'],
            ['code' => '92000', 'description' => 'Gambling and betting activities', 'category' => 'Recreation'],
            ['code' => '93110', 'description' => 'Operation of sports facilities', 'category' => 'Sports'],
            ['code' => '93120', 'description' => 'Activities of sports clubs', 'category' => 'Sports'],
            ['code' => '93190', 'description' => 'Other sports activities', 'category' => 'Sports'],
            ['code' => '93210', 'description' => 'Activities of amusement parks and theme parks', 'category' => 'Recreation'],
            ['code' => '93290', 'description' => 'Other amusement and recreation activities n.e.c.', 'category' => 'Recreation'],

            // Other Service Activities
            ['code' => '94110', 'description' => 'Activities of business and employers\' membership organizations', 'category' => 'Membership Organizations'],
            ['code' => '94120', 'description' => 'Activities of professional membership organizations', 'category' => 'Membership Organizations'],
            ['code' => '94200', 'description' => 'Activities of trade unions', 'category' => 'Membership Organizations'],
            ['code' => '94910', 'description' => 'Activities of religious organizations', 'category' => 'Religious Organizations'],
            ['code' => '94920', 'description' => 'Activities of political organizations', 'category' => 'Political Organizations'],
            ['code' => '94990', 'description' => 'Activities of other membership organizations n.e.c.', 'category' => 'Membership Organizations'],
            ['code' => '95110', 'description' => 'Repair of computers and peripheral equipment', 'category' => 'Repair Services'],
            ['code' => '95120', 'description' => 'Repair of communication equipment', 'category' => 'Repair Services'],
            ['code' => '95210', 'description' => 'Repair of consumer electronics', 'category' => 'Repair Services'],
            ['code' => '95220', 'description' => 'Repair of household appliances and home and garden equipment', 'category' => 'Repair Services'],
            ['code' => '95230', 'description' => 'Repair of footwear and leather goods', 'category' => 'Repair Services'],
            ['code' => '95240', 'description' => 'Repair of furniture and home furnishings', 'category' => 'Repair Services'],
            ['code' => '95290', 'description' => 'Repair of other personal and household goods', 'category' => 'Repair Services'],
            ['code' => '96010', 'description' => 'Washing and (dry-) cleaning of textile- and fur products', 'category' => 'Personal Services'],
            ['code' => '96021', 'description' => 'Hairdressing', 'category' => 'Personal Services'],
            ['code' => '96022', 'description' => 'Beauty treatment', 'category' => 'Personal Services'],
            ['code' => '96030', 'description' => 'Funeral and related activities', 'category' => 'Personal Services'],
            ['code' => '96090', 'description' => 'Other personal service activities n.e.c.', 'category' => 'Personal Services'],

            // Activities of Households and Extraterritorial Organizations
            ['code' => '97000', 'description' => 'Activities of households as employers of domestic personnel', 'category' => 'Household Activities'],
            ['code' => '98100', 'description' => 'Undifferentiated goods-producing activities of private households for own use', 'category' => 'Household Activities'],
            ['code' => '98200', 'description' => 'Undifferentiated service-producing activities of private households for own use', 'category' => 'Household Activities'],
            ['code' => '99011', 'description' => 'Activities of extraterritorial organizations and bodies', 'category' => 'Extraterritorial'],
            ['code' => '99012', 'description' => 'Representatives of foreign countries', 'category' => 'Extraterritorial'],
            ['code' => '99013', 'description' => 'Not economically active people, beggars, people living from handouts and charity, etc.', 'category' => 'Not Economically Active'],
            ['code' => '99014', 'description' => 'Unemployed people, people seeking work, etc.', 'category' => 'Not Economically Active'],
        ];

        $sic7Codes = array_map(function ($code) use ($now) {
            $code['created_at'] = $now;
            $code['updated_at'] = $now;

            return $code;
        }, $sic7Codes);

        DB::table('sic7_codes')->upsert(
            $sic7Codes,
            ['code'],
            ['description', 'category', 'updated_at']
        );
    }
}