name: Daily Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  build:
    name: scan docker image with trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull Docker Image
        run: |
          docker pull 248032057692.dkr.ecr.us-east-1.amazonaws.com/clearpaywebapp:latest

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: '248032057692.dkr.ecr.us-east-1.amazonaws.com/clearpaywebapp:latest'
          format: 'table'
          output: 'trivy-report.txt'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
