name: OWASP ZAP Scan

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * 1'

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Reports Directory
        run: |
          mkdir -p reports
          chmod -R 777 reports
      
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            --user root \
            -v ${{ github.workspace }}/reports:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t https://stage.rcclearpay.co.za/ \
            -r report.html

      - name: Debug Workspace
        run: |
          pwd
          echo "=== REPORTS FOLDER ==="
          ls -lah reports || true
          echo "=== WORKSPACE ==="
          find . -name "*.html" -type f
          echo "=== ZAP WRK ==="
          docker run --rm \
            -v ${{ github.workspace }}/reports:/zap/wrk:rw \
            alpine ls -lah /zap/wrk

      - name: Verify Report
        run: |
          ls -la reports

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: clearpay-stage-web-zap-report-${{ env.DATE }}
          path: reports/report.html
          